### ISSUE TITLE
Feature request: Ability to enable a drop down to pick between users

### ISSUE THREAD

**Issue by FeikoJoosten** [custom-cards/spotify-card#122]
Would be really great if a dropdown could be added which'll allow you to easily switch between users. This allows me to reuse the same card on my tablet for all the people in the house. 

Example mockup
![image](https://user-images.githubusercontent.com/10920052/97977464-8a8d9300-1dcc-11eb-8062-6c8de87ec614.png)

**Comment by FL550** [comment]
I'll have a look into this the next days.

**Comment by FL550** [comment]
Sorry for the late reply, I am very busy at the moment. Unfortunately this will take a bit more time, as right now the account handling isn't designed to be changed dynamically.

**Comment by FeikoJoosten** [comment]
Np, can understand that might be a big change. As you'll have to go through the initialization process again on account swap haha.

**Comment by FL550** [comment]
One suggestion: Is it possible that you put the cards for the different accounts on multiple tabs? This way, we don't have to change a lot of the code and it's seems right now you are the only person with this request :)

**Comment by FeikoJoosten** [comment]
Unfortunately no, I'm planning to use this card for the tablet in the living room. The purpose of that tablet is to generalize everything. But if it's not possible for now that's no biggy. There's no haste to this 😉

**Comment by FL550** [comment]
Ok, than i'll try to implement this 👍

**Comment by FeikoJoosten** [comment]
Thanks! And just take your time!

**Comment by peterjuras** [comment]
First of all, thank you for creating this card - I really love it 🙏 ❤️ 

I wanted to offer a workaround that I am currently using to switch between spotify users for this card. While I would also appreciate a native dropdown within the card, I solved it with a separate `input_select` and conditional cards in my dashboard.

This way, I get a different spotify card depending on which user is currently selected:

[Example video](https://imgur.com/D4VoitS)

Example code:
```yaml
# configuration.yaml

input_select:
  spotify_user_selection:
    name: Spotify User
    options:
      - Sandra
      - Peter
    initial: Sandra

spotcast:
  sp_dc: !secret spotcast_sp_dc_peter
  sp_key: !secret spotcast_sp_key_peter
  accounts:
    sandra:
      sp_dc: !secret spotcast_sp_dc_sandra
      sp_key: !secret spotcast_sp_key_sandra

# Dashboard code

views:
  - panel: true
    path: rutzheim
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: input_select.spotify_user_selection
                state: Peter
            card:
              type: 'custom:spotify-card'
              limit: 10
              spotify_entity: media_player.spotify_peter_juras
              account: default
              always_play_random_song: true
              grid_covers_per_row: 5
              display_style: grid
              default_device: Wohnzimmer speaker
              playlist_type: discover-weekly
          - type: conditional
            conditions:
              - entity: input_select.spotify_user_selection
                state: Sandra
            card:
              type: 'custom:spotify-card'
              limit: 10
              spotify_entity: media_player.spotify_peter_juras
              always_play_random_song: true
              grid_covers_per_row: 5
              display_style: grid
              default_device: Wohnzimmer speaker
              account: sandra
              playlist_type: discover-weekly
          - type: entities
            entities:
              - entity: input_select.spotify_user_selection
                icon: 'hass:spotify'
                name: Spotify User
            show_header_toggle: false
            state_color: false
```
