### ISSUE TITLE
Card not working properly on companion app

### ISSUE THREAD

**Issue by mcvicthor** [custom-cards/spotify-card#189]
Card does not seem to work well in the companion app if the card is anything else but in panel mode single card. If put in a vertical stack it will stop showing current playing song and playlist, controls will fail calling the service (tapping on a playlist will continue starting the player).

In browser it works fine in any setup.

what works:
```
  - theme: Backend-selected
    title: Spotify
    path: spotify
    type: panel
    layout: {}
    badges: []
    cards:
      - type: custom:spotify-card
        limit: 20
        hide_top_header: true
        always_play_random_song: true
```

what does not work properly in the companion app:
```
  - theme: Backend-selected
    title: Spotify
    path: spotify
    type: panel
    layout: {}
    badges: []
    cards:
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: custom:spotify-card
            limit: 20
            hide_top_header: true
            always_play_random_song: true
```
