### ISSUE TITLE
country code not anymore working

### ISSUE THREAD

**Issue by mfabiani53** [custom-cards/spotify-card#209]
It seems the country_code option is not anymore working..
Every country code i insert in yaml config i always get italian playlists (i am italian)

**Environment (please complete the following information):**

 - HA version: [2024.1.5 ]
 - spotcast version: [latest ]

**Configuration**

Just an example...
```
          - type: 'custom:spotify-card'
            client_id: bba03848ab0a41a3a88434389a515a86
            limit: 20
            name: Playlists Israele
            always_play_random_song: true
            height: 400
            playlist_type: featured
            country_code: 'IL'
            display_style: Grid
            filter_devices:
              - Salotto
              - Camera da letto
 ```
