### ISSUE TITLE
No card type configured.

### ISSUE THREAD

**Issue by coenboomkamp** [custom-cards/spotify-card#35]
Hi Niklas,

I’m still getting this error. Got it installed with HACS, latest version (1.10). And added it to the lovelace config:
resources:
  - type: module
    url: /community_plugin/spotify-card/spotify-card.js

The script is also properly loaded, i see it in the network tab under the developer panel in chrome.
Took out the client id for obvious reasons.

cards:
  - type: 'custom:spotify-card'
    client_id: asdfasdfasdfasdfasdfasdf
    limit: 10

Also added the redirect uri’s.

Any idea?
![image](https://user-images.githubusercontent.com/34875500/71073578-f0efcf80-2180-11ea-9332-83dca7d9745b.png)

![image](https://user-images.githubusercontent.com/34875500/71073139-17f9d180-2180-11ea-8581-779275999dce.png)

**Comment by coenboomkamp** [comment]
Sorry my bad, for others, add a manual card and add this:
type: 'custom:spotify-card'
client_id: asdfasdfasdfasdfasdfasdf
limit: 10
featuredPlaylists: false
device: media_player.keuken_sonos
player: Keuken - Sonos
height: 300

**Comment by fondberg** [comment]
I don't see a difference other than that you added more optional params. Can you highlight the difference?

**Comment by coenboomkamp** [comment]
Difference is that i tried to add that code to a manual card, instead of adding it straight to the lovelace config.
So this is for the lovelace config, described in your documentation:
```
  cards:
    - type: 'custom:spotify-card'
      client_id: <YOUR CLIENT ID>
      limit: <optional number of playlists to retrieve (default 10)>
      device: <optional name of a device to pre-select>
      player: <optional use this player only, value should be the same name as the displayname of the player>
      featuredPlaylists: <optional show featured playlists instead of users playlists>
      height: <optional pixels height for the playlist element. If content is larger scrolling will be enabled>
```
And this is for a manual card:
```
type: 'custom:spotify-card'
client_id: asdfasdfasdfasdfasdfasdf
limit: <optional number of playlists to retrieve (default 10)>
device: <optional name of a device to pre-select>
player: <optional use this player only, value should be the same name as the displayname of the player>
featuredPlaylists: <optional show featured playlists instead of users playlists>
height: <optional pixels height for the playlist element. If content is larger scrolling will be enabled>
```
Sorry still learning haha!
