### ISSUE TITLE
Stops playing after spotify token refresh

### ISSUE THREAD

**Issue by JanuszMarek** [custom-cards/spotify-card#75]
Hello,
I have a problem that after token refreshing (~1h of playing) music stops playing. I am correctly redirected after authentication. I am using your integration spotcast v3.0.0 and card v1.25.0
I have Spotify Premium. I have HA 0.110.4.

configuration.yaml

```
 spotify:
   client_id: !secret spotify_client_id
   client_secret: !secret spotify_secret
 spotcast:
   sp_dc: !secret spotify_sp_dc
   sp_key: !secret spotify_sp_key
```

lovelace.yaml
```
cards:
  - type: 'custom:spotify-card'
    client_id: !secret spotify_client_id
    featuredPlaylists: true
    featuredPlaylistsCountryCode: pl
    random_song: true
```

 There is a screnshot from Developer Console
![image](https://user-images.githubusercontent.com/46564229/83903320-37041400-a75e-11ea-96fa-4015c4042272.png)
